faf62d807f02
*** Reading local file: /opt/airflow/logs/dag_id=realtime_data/run_id=manual__2023-06-06T22:34:54.665027+00:00/task_id=load_data/attempt=1.log
[2023-06-06 22:35:01,906] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: realtime_data.load_data manual__2023-06-06T22:34:54.665027+00:00 [queued]>
[2023-06-06 22:35:01,919] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: realtime_data.load_data manual__2023-06-06T22:34:54.665027+00:00 [queued]>
[2023-06-06 22:35:01,920] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-06 22:35:01,921] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-06-06 22:35:01,926] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-06 22:35:01,954] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data> on 2023-06-06 22:34:54.665027+00:00
[2023-06-06 22:35:01,960] {standard_task_runner.py:52} INFO - Started process 104 to run task
[2023-06-06 22:35:01,964] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'realtime_data', 'load_data', 'manual__2023-06-06T22:34:54.665027+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_flights_final.py', '--cfg-path', '/tmp/tmpr_hs3dsr', '--error-file', '/tmp/tmp2gmycwjh']
[2023-06-06 22:35:01,966] {standard_task_runner.py:80} INFO - Job 207: Subtask load_data
[2023-06-06 22:35:01,984] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:532: DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)

[2023-06-06 22:35:02,047] {task_command.py:371} INFO - Running <TaskInstance: realtime_data.load_data manual__2023-06-06T22:34:54.665027+00:00 [running]> on host faf62d807f02
[2023-06-06 22:35:02,093] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-06 22:35:02,188] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CynthiaA
AIRFLOW_CTX_DAG_ID=realtime_data
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-06T22:34:54.665027+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-06T22:34:54.665027+00:00
[2023-06-06 22:35:02,190] {logging_mixin.py:115} INFO - Cargando la data para la fecha: 2023-06-06 22
[2023-06-06 22:35:30,392] {python.py:173} INFO - Done. Returned value was: None
[2023-06-06 22:35:30,431] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=realtime_data, task_id=load_data, execution_date=20230606T223454, start_date=20230606T223501, end_date=20230606T223530
[2023-06-06 22:35:30,466] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-06-06 22:35:30,511] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check

